### ISSUE TITLE
trailing space after the cross reference on PDF output

### ISSUE THREAD

**Issue by hdocmsu** [leovan/quarto-pseudocode#6]
Hi @leovan, thanks for developing the pseudocode extension. 

* For the PDF output, there is a trailing white space after the cross-reference and before the period (.). I was wondering if you are able to fix it? You can see it from the figure you shared in the Readme.
![image](https://github.com/user-attachments/assets/8d528516-9363-4830-bd16-bf17f709594c)

* I tried the EPUB output, but the pseudocode is not rendered with EPUB. Oddly, the cross-reference from different files works on EPUB. I am not sure if it may give you a hint to fix the bug for HTML, where the cross-reference from different files does not work.

**Comment by hdocmsu** [comment]
FYI, there is a discussion on Quaro-cli related to this extension. it would be great if you could fix the bugs and make this repo to be an official ext for  Quaro. 

https://github.com/quarto-dev/quarto-cli/discussions/3049

**Comment by leovan** [comment]
The first bug will be fix soon. Filter is not fully tested with EPUB output, so it may not work with it. PR is welcome to make this filter compatible with EPUB output.

**Comment by hdocmsu** [comment]
Thanks, yes, the first bug is FIXED!
