### ISSUE TITLE
Quarto中文使用者的自定义中文字体问题

### ISSUE THREAD

**Issue by MaxforCherubim** [leovan/quarto-pseudocode#7]
- 你好大佬，我是在quarto ver1.5.6版本的中文bug这个issue了解到您的。
- 当时我看到由您提交的issue，最终quarto的负责人修复了这个bug并似乎提交修复了。
- 现在我时隔几个月重新打开quarto并更新为1.5.7后，中文bug是得到解决，但是pdf自定义中文字体始终无法实现。
- 我之前是有在beamer中自定义了字体，现在重新render这个beamer的qmd，竟然无法运行。
---
- 苦恼的我最终想到请教您，但是没找到您的邮箱，好像github似乎也无法私信，所以只能跑到这里发issue询问。
- 想请教您平时是如何使用quarto来生成中文文档的。

**Comment by leovan** [comment]
PDF 自定义字体你可以参考 LaTeX 的相关中文设置，我也不是很熟悉，不是这里的 issue，我就关闭了
